-- ORDER BY & DISTINCT -- 

--  SELECT DATA WITH ORDER BY
SELECT * FROM INFO1 
ORDER BY Name,City;
SELECT * FROM PERSON 
ORDER BY DOB;
SELECT * FROM INFO1 
ORDER BY Age desc; -- THE DEFUALT VALUES IS ASC ORDER  


-- SELECT DATA WITH DISTINCT 
SELECT DISTINCT City FROM INFO1;
SELECT DISTINCT Age FROM INFO1 ORDER BY Age;