--                    STRING FUNCTIONS - II
-- 1>SUBSTRING() / SUBSTR()
-- 2>MID()
-- 3>LEFT()
-- 4>RIGHT()
-- 5>LPAD() 
-- 6>SPACE
-- 7>REVERSE()
-- 8>REPEAT()
-- 9>REPLACE()
-- 10>STRCMP()
-- 11>FIELD()
-- 12>FIND_IN_SET
-- 13>FORMAT()
-- 14>HEX()
-- 15>SUBSTRING_INDEX()

-- 1>SUBSTRING() / SUBSTR()
SELECT SUBSTRING("MUNEEB HASSAN DEVELOPER",-6,10) AS SUBSTRING_FUNCTIONS;
SELECT SUBSTR("MUNEEB HASSAN DEVELOPER",-6,10) AS SUBSTR_FUNCTIONS;

-- 2>MID()
SELECT MID("MUNEEB HASSAN DEVELOPER",-6,10) AS MID_FUNCTION;

-- 3>SUBSTRING_INDEX()
SELECT SUBSTRING_INDEX("HELLO.WWW.VIP.ID", "." ,3) AS SUBSTRING_INDEX_FUNCTIONS;

-- 4>LEFT()
SELECT LEFT("MUNEEB HASSAN",5) AS LEFT_FUNCTION;

-- 5>RIGHT()
SELECT RIGHT("MUNEEB HASSAN",5) AS RIGHT_FUNCTION;

-- 6>RPAD()
SELECT RPAD("HELLO MUNEEB HASSAN", 30 ,"-") AS RPAD; 

-- 7>LPAD() 
SELECT LPAD("HELLO MUNEEB HASSAN", 30 ,"-") AS LPAD; 

-- 8>SPACE
SELECT SPACE(100) AS SPACES_FUNCTIONS;

-- 9>REVERSE 
SELECT REVERSE("muneeB") AS REVERSE_FUNCTIONS;

-- 10>REPLACE
SELECT REPLACE("HELLO EVERY BUDDY HOW ARE YOU","HELLO","H! Muneeb") AS REPLACE_FUNCTION;

-- 11>STRCMP()
SELECT STRCMP("HELLO MUNEEB" , "HELLO MUNEEB") AS STRCMP_FUNCTIONS;

-- 12>FIELD()
SELECT FIELD("A", "HELLO EVerY BUDDY","A") AS FIELD_FUNCTION;

-- 13>FIND_IN_SET
SELECT FIND_IN_SET("MUNEEB", "ALI,MUNEEB,HASSAN,kASIF,UBAID") AS FIND_IN_SET_FUNCTION;

-- 14>FORMAT()
SELECT FORMAT(893292.28382993489328423940,4) AS FORMAT_FUNCTIONS;

-- 15>HEX()
SELECT HEX("HEXA FROM");