--                                                      MySQL ALTER COMMAND

-- 1>ALTER ADD COLUMN
ALTER TABLE PERSONAL
ADD COLUMN Email VARCHAR(200);

ALTER TABLE PERSONAL 
ADD UNIQUE (Email);

-- 2>ALTER MODIFY COLUMN
ALTER TABLE PERSONAL 
MODIFY COLUMN Email VARCHAR(200)
AFTER Name;

-- 3>ALTER CHANGE COLUMN NAME 
ALTER TABLE PERSONAL 
CHANGE Email Email_Pr VARCHAR(200);

-- 4>ALTER DELETE COLUMN 
ALTER TABLE PERSONAL
DROP column Email_pr;

-- 5>ALTER RENAME TABLE NAME
ALTER TABLE PERSONAL 
RENAME STUDENTS;

-- 6>ALTERING THE CONSTRAINTS
ALTER TABLE COURSES 
AUTO_INCREMENT = 7;